
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: leeyen
# brief-intro: Front-end Dev Engineer
brief-intro: leeyen的主页
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liyan0411.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: leeyen

github_username:  liyan0411.github
email: minchao19920917@126.com
weibo_username: leeyen

description_footer: Copyright &copy; 2016-2018 闵超 All rights reserved.



markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: Categories/
tag_dir: Tags/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 2


#Local Server Port
port: 3000
#Local Server Hostname
host: localhost